### PR TITLE
use cloudflare cdnjs

### PR DESCRIPTION
**Pull request by anjia0532**
in china, we cannot access all of the google site.

### CODE REVIEW

**Comment by rcasey212** [comment]
Hi @anjia0532, I understand your situation.  I would accept a PR that allows the URL for these components to be configured via a configuration file, but keeps the default (if you specify nothing) as the ajax.googleapis.com location.  If you can submit a PR that does that, I will accept it.  Thanks!

**Comment by anjia0532** [comment]
sorry,I have not used ng. I want but I can't.

**Comment by rcasey212** [comment]
Understood.  Sorry, I cannot accept this as-is.

**Comment by VictorZeng** [comment]
@anjia0532 see https://github.com/DarkPhoenixs/kafka-offset-monitor

**Comment by anjia0532** [comment]
thanks for your job,i konw how to fix this . but how to keep in sync with the master branch?

**Comment by VictorZeng** [comment]
@anjia0532 I will do this

**Pull request closed without merging**
